openapi: 3.0.3
info:
  title: Performance Reports
  version: '1.0'
paths:
  /restapi/v1.0/account/{accountId}/analytics/performance/calls/aggregate:
    post:
      description: Returns call performance aggregations filtered by parameters specified.
      operationId: aggregatePerformanceReportCalls
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: The current page number.
        required: false
        schema:
          type: integer
          minimum: 1
      - name: perPage
        in: query
        description: How many items are displayed on the page.
        required: false
        schema:
          type: integer
          minimum: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformanceCallsAggregatesRequest'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceCallsAggregatesResponse'
              examples:
                Sample response with grouping:
                  summary: A request for count of calls by result and direction grouped
                    by queues will return the following response.
                  value:
                    data:
                      '9997317575':
                        counters:
                          callsByDirection:
                            inbound: 60
                            outbound: 90
                          callsByResult:
                            completed: 10
                            abandoned: 20
                            voiceMail: 40
                            connected: 50
                      '8997317575':
                        counters:
                          callsByDirection:
                            inbound: 21
                            outbound: 7
                          callsByResult:
                            completed: 0
                            abandoned: 0
                            voiceMail: 11
                            connected: 7
                    paging:
                      page: 1
                      perPage: 2
                      totalPages: 150
                      totalElements: 299
                Sample response without grouping:
                  summary: A request with empty grouping, calls timer by direction
                    and call duration will return the following response with data
                    for the entire account.
                  value:
                    data:
                      '8557317575':
                        timers:
                          callsDurationSeconds: 1000
                          callsByDirection:
                            inboundCallsSeconds: 700
                            outboundCallsSeconds: 300
                    paging:
                      page: 1
                      perPage: 55
                      totalPages: 1
                      totalElements: 1
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestResponse'
              examples:
                Query parameter is invalid:
                  value:
                    errors:
                    - errorCode: CMN-101
                      message: page
                Invalid Parameter:
                  value:
                    errors:
                    - errorCode: CMN-101
                      message: Parameter [parameterName] value is invalid.
                Multiple Invalid Parameters:
                  value:
                    errors:
                    - errorCode: CMN-101
                      message: Parameter [parameter1] value is invalid.
                    - errorCode: CMN-101
                      message: Parameter [parameter2] value is invalid.
                Parse error:
                  value:
                    errors:
                    - errorCode: CMN-103
                      message: JSON can't be parsed
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'
              examples:
                Server error:
                  value:
                    errors:
                    - errorCode: CMN-206
                      message: 'Internal server error, request ID: [00000000-0000-0000-0000-000000000001]'
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginToExtensionRequiredErrorResponse'
              examples:
                Login required:
                  value:
                    errors:
                    - errorCode: CMN-405
                      message: Login to extension required
components:
  schemas:
    AggregationMethod:
      type: string
      enum:
      - Sum
      - Average
      - Max
      - Min
    CallAction:
      type: string
      enum:
      - HoldOff
      - HoldOn
      - ParkOn
      - ParkOff
      - BlindTransfer
      - WarmTransfer
      - DTMFTransfer
    CallActionFilter:
      required:
      - callAction
      type: object
      properties:
        callAction:
          $ref: '#/components/schemas/CallAction'
    CallDurationByCompanyHours:
      required:
      - businessHoursSeconds
      - afterHoursSeconds
      type: object
      properties:
        businessHoursSeconds:
          type: integer
          format: int64
        afterHoursSeconds:
          type: integer
          format: int64
    CallDurationByQueueSLa:
      required:
      - inSla
      - outOfSla
      type: object
      properties:
        inSla:
          type: integer
          format: int64
        outOfSla:
          type: integer
          format: int64
    CallDurationByResponse:
      required:
      - answeredCallsSeconds
      - notAnsweredCallsSeconds
      type: object
      properties:
        answeredCallsSeconds:
          type: integer
          format: int64
        notAnsweredCallsSeconds:
          type: integer
          format: int64
    CallDurationByResponseType:
      required:
      - inboundDirectSeconds
      - parkRetrievalsSeconds
      - queueCallsSeconds
      - transferredCallsSeconds
      - missedCallsSeconds
      - acceptedCallsSeconds
      type: object
      properties:
        inboundDirectSeconds:
          type: integer
          format: int64
        parkRetrievalsSeconds:
          type: integer
          format: int64
        queueCallsSeconds:
          type: integer
          format: int64
        transferredCallsSeconds:
          type: integer
          format: int64
        missedCallsSeconds:
          type: integer
          format: int64
        acceptedCallsSeconds:
          type: integer
          format: int64
    CallDurationByResult:
      required:
      - completedCallsSeconds
      - abandonedCallsSeconds
      - voiceMailCallsSeconds
      - connectedCallsSeconds
      type: object
      properties:
        completedCallsSeconds:
          type: integer
          format: int64
        abandonedCallsSeconds:
          type: integer
          format: int64
        voiceMailCallsSeconds:
          type: integer
          format: int64
        connectedCallsSeconds:
          type: integer
          format: int64
    CallResponse:
      type: string
      description: Aggregation of calls by first response.
      enum:
      - Answered
      - NotAnswered
    CallResponseType:
      type: string
      enum:
      - InboundDirect
      - ParkRetrievals
      - QueueCalls
      - Transferred
      - Missed
      - Accepted
    CallResultType:
      type: string
      enum:
      - Completed
      - Abandoned
      - VoiceMail
      - Connected
    CallSegment:
      type: string
      enum:
      - Ringing
      - LiveTalk
      - Hold
      - Park
      - Transfer
      - IvrPrompt
      - VoiceMailing
      - VmGreeting
    CallSegmentFilter:
      required:
      - callSegment
      type: object
      properties:
        callSegment:
          $ref: '#/components/schemas/CallSegment'
    CallsActionsCount:
      required:
      - parksOn
      - parksOff
      - holdsOn
      - holdsOff
      - blindTransfer
      - warmTransfer
      - dtmftTransfer
      type: object
      properties:
        parksOn:
          type: integer
          format: int64
        parksOff:
          type: integer
          format: int64
        holdsOn:
          type: integer
          format: int64
        holdsOff:
          type: integer
          format: int64
        blindTransfer:
          type: integer
          format: int64
        warmTransfer:
          type: integer
          format: int64
        dtmftTransfer:
          type: integer
          format: int64
    CallsByCompanyHours:
      required:
      - businessHours
      - afterHours
      type: object
      properties:
        businessHours:
          type: integer
          format: int64
        afterHours:
          type: integer
          format: int64
    CallsByDirection:
      required:
      - inbound
      - outbound
      type: object
      properties:
        inbound:
          type: integer
          format: int64
        outbound:
          type: integer
          format: int64
    CallsByOrigin:
      required:
      - internal
      - external
      type: object
      properties:
        internal:
          type: integer
          format: int64
        external:
          type: integer
          format: int64
    CallsByQueueSla:
      required:
      - inSla
      - outOfSla
      type: object
      properties:
        inSla:
          type: integer
          format: int64
        outOfSla:
          type: integer
          format: int64
    CallsByResponse:
      required:
      - answered
      - notAnswered
      type: object
      properties:
        answered:
          type: integer
          format: int64
        notAnswered:
          type: integer
          format: int64
    CallsByResponseType:
      required:
      - inboundDirect
      - parkRetrieval
      - queueCalls
      - transferredCalls
      - missed
      - accepted
      type: object
      properties:
        inboundDirect:
          type: integer
          format: int64
        parkRetrieval:
          type: integer
          format: int64
        queueCalls:
          type: integer
          format: int64
        transferredCalls:
          type: integer
          format: int64
        missed:
          type: integer
          format: int64
        accepted:
          type: integer
          format: int64
    CallsByResult:
      required:
      - completed
      - abandoned
      - voiceMail
      - connected
      type: object
      properties:
        completed:
          type: integer
          format: int64
        abandoned:
          type: integer
          format: int64
        voiceMail:
          type: integer
          format: int64
        connected:
          type: integer
          format: int64
    CallsBySegments:
      required:
      - ringing
      - liveTalk
      - holds
      - parks
      - transfers
      - ivrPrompts
      - voiceMailing
      - vmGreetings
      type: object
      properties:
        ringing:
          type: integer
          format: int64
        liveTalk:
          type: integer
          format: int64
        holds:
          type: integer
          format: int64
        parks:
          type: integer
          format: int64
        transfers:
          type: integer
          format: int64
        ivrPrompts:
          type: integer
          format: int64
        voiceMailing:
          type: integer
          format: int64
        vmGreetings:
          type: integer
          format: int64
    CallsDurationByDirection:
      required:
      - inboundCallsSeconds
      - outboundCallsSeconds
      type: object
      properties:
        inboundCallsSeconds:
          type: integer
          format: int64
        outboundCallsSeconds:
          type: integer
          format: int64
    CallsDurationByOrigin:
      required:
      - internalCallsSeconds
      - externalCallsSeconds
      type: object
      properties:
        internalCallsSeconds:
          type: integer
          format: int64
        externalCallsSeconds:
          type: integer
          format: int64
    Direction:
      type: string
      description: Specifies whether the call was inbound or outbound relative to
        the account. Not applicable to internal calls.
      enum:
      - Inbound
      - Outbound
    ErrorBody:
      required:
      - errorCode
      - message
      type: object
      properties:
        errorCode:
          type: string
        message:
          type: string
    GroupingOptions:
      type: string
      description: This field describes the dimensions by which the response should
        be grouped.
      enum:
      - CompanyNumbers
      - Users
      - Queues
      - IVRs
      - UserGroups
      - Sites
      - Departments
      - DepartmentMembers
      - UserGroupMembers
      - QueueAgents
      - SiteMembers
    InternalServerErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorBody'
    InvalidRequestResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorBody'
    LoginToExtensionRequiredErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorBody'
    Map_PerformanceCallsData:
      type: object
      description: Mapping of call aggregations as per the grouping and filtering
        options specified in the request.
      additionalProperties:
        $ref: '#/components/schemas/PerformanceCallsData'
    Origin:
      type: string
      description: Specifies whether the call originated within the account or outside
        of it.
      enum:
      - Internal
      - External
    PerformanceCallsAggregatesRequest:
      required:
      - timeRange
      - responseOptions
      type: object
      properties:
        grouping:
          $ref: '#/components/schemas/PerformanceCallsGrouping'
        timeRange:
          $ref: '#/components/schemas/PerformanceCallsTimeRange'
        additionalFilters:
          $ref: '#/components/schemas/PerformanceCallsFilters'
        responseOptions:
          $ref: '#/components/schemas/PerformanceCallsResponseDataOptions'
    PerformanceCallsAggregatesResponse:
      required:
      - data
      - paging
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Map_PerformanceCallsData'
        paging:
          $ref: '#/components/schemas/ResponsePaging'
    PerformanceCallsCompanyHours:
      type: string
      description: Aggregation of calls by company's business hours or after hours.
      enum:
      - BusinessHours
      - AfterHours
    PerformanceCallsCounters:
      type: object
      properties:
        totalCalls:
          type: integer
          format: int64
        callsByDirection:
          $ref: '#/components/schemas/CallsByDirection'
        callsByOrigin:
          $ref: '#/components/schemas/CallsByOrigin'
        callsByResponse:
          $ref: '#/components/schemas/CallsByResponse'
        callsByResponseType:
          $ref: '#/components/schemas/CallsByResponseType'
        callsByResult:
          $ref: '#/components/schemas/CallsByResult'
        callsActionsCount:
          $ref: '#/components/schemas/CallsActionsCount'
        callsBySegments:
          $ref: '#/components/schemas/CallsBySegments'
        callsByCompanyHours:
          $ref: '#/components/schemas/CallsByCompanyHours'
        callsByQueueSla:
          $ref: '#/components/schemas/CallsByQueueSla'
      description: Call volume data for the specified grouping.
    PerformanceCallsCountersResponseOptions:
      type: object
      properties:
        allCalls:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByDirection:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByOrigin:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByResponse:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByResponseType:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsBySegment:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByResult:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByActions:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByCompanyHours:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsByQueueSla:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
    PerformanceCallsData:
      type: object
      properties:
        timers:
          $ref: '#/components/schemas/PerformanceCallsTimers'
        counters:
          $ref: '#/components/schemas/PerformanceCallsCounters'
    PerformanceCallsFilterByLength:
      type: object
      properties:
        minValueSeconds:
          type: integer
          format: int64
        maxValueSeconds:
          type: integer
          format: int64
      description: Conditional aggregation of calls based on the overall call length.
    PerformanceCallsFilterTimeSpentByMailbox:
      type: object
      properties:
        minValueSeconds:
          type: integer
          format: int64
        maxValueSeconds:
          type: integer
          format: int64
      description: Conditional aggregation of calls based on the time spent by specified
        mailbox(es) on call.
    PerformanceCallsFilters:
      type: object
      properties:
        direction:
          $ref: '#/components/schemas/Direction'
        origin:
          $ref: '#/components/schemas/Origin'
        callResponse:
          $ref: '#/components/schemas/CallResponse'
        callResponseType:
          type: array
          items:
            $ref: '#/components/schemas/CallResponseType'
          description: A list of call response types (joined via OR).
        callResult:
          type: array
          items:
            $ref: '#/components/schemas/CallResultType'
          description: Aggregation of calls by the nature of call result (joined via
            OR).
        callSegments:
          type: array
          items:
            $ref: '#/components/schemas/CallSegmentFilter'
          description: Aggregation of calls by presence of specific segment (joined
            via OR).
        callActions:
          type: array
          items:
            $ref: '#/components/schemas/CallActionFilter'
          description: Aggregation of calls by presence of specific action (joined
            via OR).
        companyHours:
          $ref: '#/components/schemas/PerformanceCallsCompanyHours'
        callDuration:
          $ref: '#/components/schemas/PerformanceCallsFilterByLength'
        timeSpent:
          $ref: '#/components/schemas/PerformanceCallsFilterTimeSpentByMailbox'
        callerExtensionIds:
          type: array
          items:
            type: string
          description: List of extension Ids from which users specified in groupBy
            received calls, items are joined via OR condition.
        calledExtensionIds:
          type: array
          items:
            type: string
          description: List of extension Ids to which users specified in groupBy placed
            calls, items are joined via OR condition.
        calledNumbers:
          type: array
          items:
            type: string
          description: The direct numbers the caller called (joined via OR).
        queueSla:
          $ref: '#/components/schemas/QueueSla'
      description: Optional filters that limit the scope of calls to be aggregated
        (joined via AND [UNION]).
    PerformanceCallsGrouping:
      required:
      - groupBy
      type: object
      properties:
        groupBy:
          $ref: '#/components/schemas/GroupingOptions'
        ids:
          type: array
          items:
            type: string
          description: This field can be used to specify unique identifiers of groups
            in GroupBy types. This is a required field for DepartmentMembers, UserGroupMembers,
            QueueAgents and SiteMembers groupings.
      description: Options for response grouping. This field defines the dimensions
        by which the call data will be grouped. If this field is undefined the response
        map will represent the whole company scope.
    PerformanceCallsResponseDataOptions:
      type: object
      properties:
        counters:
          $ref: '#/components/schemas/PerformanceCallsCountersResponseOptions'
        timers:
          $ref: '#/components/schemas/PerformanceCallsTimersResponseOptions'
      description: This field provides mapping of possible breakdown options for call
        aggregation and aggregation formula.
    PerformanceCallsTimeRange:
      required:
      - timeFrom
      - timeTo
      type: object
      properties:
        timeFrom:
          type: string
          description: The start date-time for resulting records in RFC 3339 format
            including timezone, for example 2016-03-10T18:07:52.534Z.
          format: date-time
        timeTo:
          type: string
          description: The end date-time for resulting records in RFC 3339 format
            including timezone, for example 2016-03-10T18:07:52.534Z.
          format: date-time
      description: Date-time range for which the calls are aggregated. The call is
        considered to be within time range if it started within time range. Both borders
        are inclusive.
    PerformanceCallsTimers:
      type: object
      properties:
        callsDurationSeconds:
          type: integer
          format: int64
        callSegmentLengthSeconds:
          $ref: '#/components/schemas/TimeSpentBySegments'
        callsByDirection:
          $ref: '#/components/schemas/CallsDurationByDirection'
        callsByOrigin:
          $ref: '#/components/schemas/CallsDurationByOrigin'
        callsByResponse:
          $ref: '#/components/schemas/CallDurationByResponse'
        callsByResult:
          $ref: '#/components/schemas/CallDurationByResult'
        callsByResponseType:
          $ref: '#/components/schemas/CallDurationByResponseType'
        callsByCompanyHours:
          $ref: '#/components/schemas/CallDurationByCompanyHours'
        callsByQueueSla:
          $ref: '#/components/schemas/CallDurationByQueueSLa'
      description: Call length data for the specified grouping.
    PerformanceCallsTimersResponseOptions:
      type: object
      properties:
        totalCallLength:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        timeSpentByCallSegments:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callLengthByDirection:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callLengthByOrigin:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callLengthByResponse:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callLengthByResponseType:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callLengthByResult:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsLengthByCompanyHours:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
        callsLengthByQueueSla:
          required:
          - aggregationType
          type: object
          properties:
            aggregationType:
              $ref: '#/components/schemas/AggregationMethod'
    QueueSla:
      type: string
      description: This filter allows to get aggregation of calls that were either
        within or out of queue SLA.
      enum:
      - InSla
      - OutSla
    ResponsePaging:
      required:
      - page
      - perPage
      - totalPages
      - totalElements
      type: object
      properties:
        page:
          type: integer
          description: The current page number.
          format: int64
        perPage:
          type: integer
          description: How many items are displayed on the page.
          format: int64
        totalPages:
          type: integer
          description: The total number of pages.
          format: int64
        totalElements:
          type: integer
          description: The total number of items in the dataset.
          format: int64
      description: Paging.
    TimeSpentBySegments:
      required:
      - ringing
      - liveTalk
      - holds
      - parks
      - transfers
      - ivrPrompts
      - voiceMailing
      - vmGreetings
      type: object
      properties:
        ringing:
          type: integer
          format: int64
        liveTalk:
          type: integer
          format: int64
        holds:
          type: integer
          format: int64
        parks:
          type: integer
          format: int64
        transfers:
          type: integer
          format: int64
        ivrPrompts:
          type: integer
          format: int64
        voiceMailing:
          type: integer
          format: int64
        vmGreetings:
          type: integer
          format: int64
x-throttling-group: Light
x-service-name: performance-reports
x-service-interface: rest
x-service-version: v1
x-api-group: analytics/performance-reports
x-internal-api: false
x-team: Analytics
x-auth-required: true
x-failover-strategy: 'Off'
x-blacklisting-strategy: 'Off'
x-rewrite-tunneled-method: true
x-docs-level: Internal
x-app-permission: Analytics
